<a href="https://colab.research.google.com/github/RaoSaeed836/Numpy/blob/main/Numpy_day_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# #numpy aik mathmatical library ha or as ma sb sa main chez ha wo ha aik array object
# E jesy python ka data type th alist asy he numpy ka data type ha aik jes ko ap numpy array khty h

In [2]:
# vector
import numpy as np
a=np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
#2d and #3d nump array
# metrics
np.array([[1,2,3,4],[5,6,7,9]])

array([[1, 2, 3, 4],
       [5, 6, 7, 9]])

In [4]:
#tensor
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [5]:
# apny pasand ka data type bna skty ho
# np.array([1,2,3],dtype=float)
np.array([1,2,3,0],dtype=bool)

array([ True,  True,  True, False])

In [6]:
# np.arange
np.arange(1,11)
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [7]:
# with reshape
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [8]:
#np.ones and np.zeros
# values ko initliaze krny ka kam aty ha dono
np.ones((3,4))
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
# random
# random value sa intiliaze krta ha
np.random.random((3,5))

array([[0.71994161, 0.00761403, 0.33558377, 0.91332449, 0.52122752],
       [0.23804342, 0.39517278, 0.31202463, 0.63507584, 0.57012502],
       [0.55373376, 0.99706381, 0.08329231, 0.05294381, 0.86892487]])

In [10]:
#linspace
#aik given range ma equal distance pr point gerntae kr ka deta ha
np.linspace(-34,34,10)
np.linspace(-34,34,10,dtype=int)

array([-34, -27, -19, -12,  -4,   3,  11,  18,  26,  34])

In [11]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

###Array ATRIBUTES

In [12]:
a=np.arange(10)
b=np.arange(12,dtype=float).reshape(3,4)
c=np.arange(8).reshape(2,2,2)
print(a)
print(b)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [13]:
#ndim
# tell use the dimension of given array
a.ndim

1

In [14]:
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [15]:
# shape
# hr dimension ma kitny  item ha

In [16]:
a.shape
b.shape
c.shape

(2, 2, 2)

In [17]:
# size
a.size
c.size

8

In [18]:
#itemsize
#hr item memory ma kitna size occupy kr rha ha
#int32 4 byte leta ha or int64 jo by defulat hotaha ya 8 bytes leta ha
a.itemsize

8

In [19]:
#dtype
#item ka data type btata ha
a.dtype
b.dtype

dtype('float64')

In [20]:
b

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

###Changing Data type

In [21]:
#astype
a.dtype
a.astype(np.int32)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

###Array opertaion's

In [22]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

In [23]:
#Scalar operation
# all arhitmetic operation work on it 2 is scalara and a1 is array
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [24]:
#relational operator
a1>5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [25]:
#vector operation
# both are the aray
a1*a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

###Array function

In [26]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[65., 89., 60.],
       [48., 47., 81.],
       [13., 59., 76.]])

In [27]:
#min/max/sum/prod
a1.min()
a1.sum()
# hr row ka min item feth kro
# 0--> column    and 1-->row
a1.min(axis=1)
a1.prod(axis=0)

array([ 40560., 246797., 369360.])

In [28]:
#mean/median/mode
a1.mean()
a1.mean(axis=1)

array([71.33333333, 58.66666667, 49.33333333])

In [29]:
# dot product
# dot product ka phly waly ka row or dosry waly ka col math krna chay
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)
np.dot(a1,a2)

array([[ 836., 1050., 1264., 1478.],
       [ 836., 1012., 1188., 1364.],
       [ 844.,  992., 1140., 1288.]])

In [30]:
# round/floor/cell
np.round(np.random.random((2,3))*100)
np.floor(np.random.random((2,3))*100)

array([[43., 78., 23.],
       [83., 95., 42.]])

###indexing and slicing

In [31]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [32]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
a1[-1]
a[5]

np.int64(5)

In [34]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
a2[1,2]  # 1st row then colimn
a2[2,3]
a2[1,3]
a2[1,0]

np.int64(4)

In [36]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [37]:
a3[1,0,1]
a3[0,1,1]
a3[0,0,0]

np.int64(0)

In [38]:
# indexing sa hm aik item ffetch kr rhy thy laken sliecning ko use kr ka hm multiple
#item ko fetch kr skty h a

In [39]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
a1[2:6]
a1[2:9:2]

array([2, 4, 6, 8])

In [41]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
a2[0,:]

array([0, 1, 2, 3])

In [43]:
a2[0:,2]
a2[1:,1:3]
a2[0:2,0:2]
a2[1:,0:4:3]
a2[0::2,0::3]
a2[0::2,1::2]
a2[1:2,0::3]

array([[4, 7]])

In [44]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [45]:
a3[1,0::,0::]
a3[1]
a3[0::2]
a3[0::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [46]:
for i in a1:
   print(i)

0
1
2
3
4
5
6
7
8
9


In [47]:
for i in a2:
   print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [48]:
for i in a3:
   print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [49]:
for i in np.nditer(a3):
   print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


###Reshaping

In [50]:
#reshape

In [51]:
#transpose
a2.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [52]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
#ravel
# kitny bhe dimension ke array ko id ma convert kr deta ha
a2.ravel()
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

###Stacking

In [54]:
# horizontal stack

# stack ka ly shape same hona zarori ha
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [55]:
#vertical stacks
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### spliting

In [56]:
# it just opposite the stack

In [57]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [58]:
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

### TASK'S

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [62]:
a=np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [91]:
# a=np.ones(16).reshape(4,4)
# a[1:3,1:3]=0
# a
def function(par):
  par[1:3,1:3]=0
  print(a)


In [90]:
par=np.ones(16).reshape(4,4)
function(par)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [110]:
a=int(input("enter the first number"))
b=int(input("enter the second number"))
c=np.random.random((a,b))
print(c)
print(c.mean())

enter the first number3
enter the second number3
[[0.065464   0.12062418 0.38797346]
 [0.09097133 0.98227776 0.39904427]
 [0.19231269 0.13401228 0.55016719]]
0.3247607960202711


###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [125]:
np.linspace(0,1,10,endpoint=False)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.


In [100]:
a=np.arange(0,12).reshape(3,4)
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [134]:
np.linspace(0,4,25,dtype=int).reshape(5,5)

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1],
       [1, 1, 2, 2, 2],
       [2, 2, 2, 3, 3],
       [3, 3, 3, 3, 4]])

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [140]:
a=np.array([23,34,56,7,889,])
a
print("elemnt count is ",a.size)

elemnt count is  5


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [152]:
def vst(srr1,srr2):
  print(srr1)
  print(srr2)
  b=np.vstack((srr1,srr2))
  return b


In [153]:
arr1=np.arange(120).reshape(10,12)
arr2=np.arange(120,240).reshape(10,12)
vst(arr1,arr2)

[[  0   1   2   3   4   5   6   7   8   9  10  11]
 [ 12  13  14  15  16  17  18  19  20  21  22  23]
 [ 24  25  26  27  28  29  30  31  32  33  34  35]
 [ 36  37  38  39  40  41  42  43  44  45  46  47]
 [ 48  49  50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71]
 [ 72  73  74  75  76  77  78  79  80  81  82  83]
 [ 84  85  86  87  88  89  90  91  92  93  94  95]
 [ 96  97  98  99 100 101 102 103 104 105 106 107]
 [108 109 110 111 112 113 114 115 116 117 118 119]]
[[120 121 122 123 124 125 126 127 128 129 130 131]
 [132 133 134 135 136 137 138 139 140 141 142 143]
 [144 145 146 147 148 149 150 151 152 153 154 155]
 [156 157 158 159 160 161 162 163 164 165 166 167]
 [168 169 170 171 172 173 174 175 176 177 178 179]
 [180 181 182 183 184 185 186 187 188 189 190 191]
 [192 193 194 195 196 197 198 199 200 201 202 203]
 [204 205 206 207 208 209 210 211 212 213 214 215]
 [216 217 218 219 220 221 222 223 224 225 226 227]
 [228 229 230 231 232 233 234 

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47],
       [ 48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71],
       [ 72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83],
       [ 84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107],
       [108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131],
       [132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143],
       [144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155],
       [156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167],
       [168, 169, 170, 171, 172, 1

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

###`Q-14:` Subtract the mean of each row from a matrix.

###`Q-15:` Swap column-1 of array with column-2 in the array.

###`Q-16:` Replace odd elements in arrays with -1.

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [59]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[ 936,  916, 7086, 7829, 7485],
       [5197, 8660, 1621, 9540, 5804],
       [7406, 1582,  683, 8826, 5543],
       [1539, 3304,  506, 7302, 9228],
       [4968, 6065,  505,  135, 1218],
       [9601, 1157, 2039, 1409, 2930],
       [1275,  867, 8632, 6108, 9906],
       [1681, 9057, 4416, 1608, 3564]])

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [178]:
a=np.array([1,2,3])
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [167]:
import numpy as np
# np.repeat(3, 4)
x = np.array([[1,2,3,4],[5,6,7,8]])
np.repeat(x, 4)
# np.repeat(x, 3, axis=1)
# np.repeat(x, [1, 2], axis=0)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6,
       6, 6, 7, 7, 7, 7, 8, 8, 8, 8])